apiVersion: v1
kind: Secret
metadata:
  name: vuln-platform-secrets
  namespace: secops-vulnerability
type: Opaque
stringData:
  JWT_SECRET: "ssdlc_vulnerability_platform_jwt_secret_production_2026_x987"
  AUDIT_HMAC_SECRET: "ssdlc_super_secret_audit_key_production_hmac_2026"
