apiVersion: v1
kind: Namespace
metadata:
  name: secops-vulnerability
  labels:
    name: secops-vulnerability
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all-ingress
  namespace: secops-vulnerability
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-platform-http-ingress
  namespace: secops-vulnerability
spec:
  podSelector:
    matchLabels:
      app: vuln-platform
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 3000
